// {
//     "Ampara": [
//       "Addalachchenai",
//       "Akkaraipattu",
//       "Alayadiwembu",
//       "Ampara",
//       "Damana",
//       "Dehiattakandiya",
//       "Eragama",
//       "Kalmunai Muslim",
//       "Kalmunai Tamil",
//       "Karaitivu",
//       "Lahugala",
//       "Mahaoya",
//       "Navithanveli",
//       "Ninthavur",
//       "Padiyathalawa",
//       "Pothuvil",
//       "Sainthamarathu",
//       "Samanthurai",
//       "Thirukkovil",
//       "Uhana"
//     ],
//     "Anuradhapura": [
//       "Galenbindunuwewa",
//       "Horowpothana",
//       "Ipalogama",
//       "Kahatagasdigiliya",
//       "Kebithigollewa",
//       "Kekirawa",
//       "Mahavilachchiya",
//       "Medawachchiya",
//       "Mihinthale",
//       "Nachchadoowa",
//       "Nochchiyagama",
//       "Nuwaragam Palatha Central",
//       "Nuwaragam Palatha East",
//       "Padaviya",
//       "Palagala",
//       "Palugaswewa",
//       "Rajanganaya",
//       "Rambewa",
//       "Thalawa",
//       "Thambuttegama",
//       "Thirappane"
//     ],
//     "Badulla": [
//       "Badulla",
//       "Bandarawela",
//       "Ella",
//       "Haldummulla",
//       "Hali-Ela",
//       "Haputale",
//       "Kandaketiya",
//       "Lunugala",
//       "Mahiyanganaya",
//       "Meegahakivula",
//       "Passara",
//       "Rideemaliyadda",
//       "Soranathota",
//       "Uva-Paranagama",
//       "Welimada"
//     ],
//     "Batticaloa": [
//       "Eravur Pattu",
//       "Eravur Town",
//       "Kattankudy",
//       "Koralai Pattu",
//       "Koralai Pattu Central",
//       "Koralai Pattu North",
//       "Koralai Pattu South",
//       "Koralai Pattu West",
//       "Manmunai North",
//       "Manmunai Pattu",
//       "Manmunai South and Eruvil Pattu",
//       "Manmunai South West",
//       "Manmunai West",
//       "Porativu Pattu"
//     ],
//     "Colombo": [
//       "Colombo",
//       "Dehiwala",
//       "Homagama",
//       "Kaduwela",
//       "Kesbewa",
//       "Kolonnawa",
//       "Kotte",
//       "Maharagama",
//       "Moratuwa",
//       "Padukka",
//       "Ratmalana",
//       "Seethawaka",
//       "Thimbirigasyaya"
//     ],
//     "Galle": [
//       "Akmeemana",
//       "Ambalangoda",
//       "Baddegama",
//       "Balapitiya",
//       "Benthota",
//       "Bope-Poddala",
//       "Elpitiya",
//       "Galle",
//       "Gonapinuwala",
//       "Habaraduwa",
//       "Hikkaduwa",
//       "Imaduwa",
//       "Karandeniya",
//       "Nagoda",
//       "Neluwa",
//       "Niyagama",
//       "Thawalama",
//       "Welivitiya-Divithura",
//       "Yakkalamulla"
//     ],
//     "Gampaha": [
//       "Attanagalla",
//       "Biyagama",
//       "Divulapitiya",
//       "Dompe",
//       "Gampaha",
//       "Ja-Ela",
//       "Katana",
//       "Kelaniya",
//       "Mahara",
//       "Minuwangoda",
//       "Mirigama",
//       "Negombo",
//       "Wattala"
//     ],
//     "Hambantota": [
//       "Ambalantota",
//       "Angunakolapelessa",
//       "Beliatta",
//       "Hambantota",
//       "Katuwana",
//       "Lunugamvehera",
//       "Okewela",
//       "Sooriyawewa",
//       "Tangalle",
//       "Thissamaharama",
//       "Walasmulla",
//       "Weeraketiya"
//     ],
//     "Jaffna": [
//       "Delft",
//       "Island North",
//       "Island South",
//       "Jaffna",
//       "Karainagar",
//       "Nallur",
//       "Thenmaradchi",
//       "Vadamaradchi East",
//       "Vadamaradchi North",
//       "Vadamaradchi South-West",
//       "Valikamam East",
//       "Valikamam North",
//       "Valikamam South",
//       "Valikamam South-West",
//       "Valikamam West"
//     ],
//     "Kalutara": [
//       "Agalawatta",
//       "Bandaragama",
//       "Beruwala",
//       "Bulathsinhala",
//       "Dodangoda",
//       "Horana",
//       "Ingiriya",
//       "Kalutara",
//       "Madurawela",
//       "Mathugama",
//       "Millaniya",
//       "Palindanuwara",
//       "Panadura",
//       "Walallavita"
//     ],
//     "Kandy": [
//       "Akurana",
//       "Delthota",
//       "Doluwa",
//       "Gangawata Korale",
//       "Ganga Ihala Korale",
//       "Harispattuwa",
//       "Hatharaliyadda",
//       "Kundasale",
//       "Medadumbara",
//       "Minipe",
//       "Panvila",
//       "Pasbage Korale",
//       "Pathadumbara",
//       "Pathahewaheta",
//       "Poojapitiya",
//       "Thumpane",
//       "Udadumbara",
//       "Udapalatha",
//       "Udunuwara",
//       "Yatinuwara"
//     ],
//     "Kegalle": [
//       "Aranayaka",
//       "Bulathkohupitiya",
//       "Dehiovita",
//       "Deraniyagala",
//       "Galigamuwa",
//       "Kegalle",
//       "Mawanella",
//       "Rambukkana",
//       "Ruwanwella",
//       "Warakapola",
//       "Yatiyanthota"
//     ],
//     "Kilinochchi": [
//       "Kandavalai",
//       "Karachchi",
//       "Pachchilaipalli",
//       "Poonakary"
//     ],
//     "Kurunegala": [
//       "Alawwa",
//       "Ambanpola",
//       "Bamunakotuwa",
//       "Bingiriya",
//       "Ehetuwewa",
//     ]
// }

const DivisionalSecretariats = {
  1: [
    { ID: 1000, Name: "Colombo" },
    { ID: 1001, Name: "Thimbirigasyaya" },
    { ID: 1002, Name: "Dehiwala" },
    { ID: 1003, Name: "Ratmalana" },
    { ID: 1004, Name: "Moratuwa" },
    { ID: 1005, Name: "Kesbewa" },
    { ID: 1006, Name: "Maharagama" },
    { ID: 1007, Name: "Kaduwela" },
    { ID: 1008, Name: "Homagama" },
    { ID: 1009, Name: "Seethawaka" },
    { ID: 1010, Name: "Padukka" },
    { ID: 1011, Name: "Hanwella" },
    { ID: 1012, Name: "Kotte" },
  ],
  2: [
    { ID: 1012, Name: "Gampaha" },
    { ID: 1013, Name: "Negombo" },
    { ID: 1014, Name: "Kelaniya" },
    { ID: 1015, Name: "Ja-Ela" },
    { ID: 1016, Name: "Minuwangoda" },
    { ID: 1017, Name: "Divulapitiya" },
    { ID: 1018, Name: "Attanagalla" },
    { ID: 1019, Name: "Biyagama" },
    { ID: 1020, Name: "Dompe" },
    { ID: 1021, Name: "Mahara" },
    { ID: 1022, Name: "Wattala" },
    { ID: 1023, Name: "Katana" },
    { ID: 1024, Name: "Mirigama" },
  ],
  3: [
    { ID: 1025, Name: "Kalutara" },
    { ID: 1026, Name: "Beruwala" },
    { ID: 1027, Name: "Panadura" },
    { ID: 1028, Name: "Horana" },
    { ID: 1029, Name: "Bandaragama" },
    { ID: 1030, Name: "Dodangoda" },
    { ID: 1031, Name: "Madurawala" },
    { ID: 1032, Name: "Ingiriya" },
    { ID: 1033, Name: "Bulathsinhala" },
    { ID: 1034, Name: "Agalawatta" },
    { ID: 1035, Name: "Mathugama" },
  ],
  4: [
    { ID: 1036, Name: "Kandy" },
    { ID: 1037, Name: "Gampola" },
    { ID: 1038, Name: "Akurana" },
    { ID: 1039, Name: "Delthota" },
    { ID: 1040, Name: "Udunuwara" },
    { ID: 1041, Name: "Yatinuwara" },
    { ID: 1042, Name: "Harispattuwa" },
    { ID: 1043, Name: "Hatharaliyadda" },
    { ID: 1044, Name: "Panwila" },
    { ID: 1045, Name: "Poojapitiya" },
    { ID: 1046, Name: "Medadumbara" },
    { ID: 1047, Name: "Ududumbara" },
  ],
  7: [
    { ID: 1048, Name: "Galle" },
    { ID: 1049, Name: "Hikkaduwa" },
    { ID: 1050, Name: "Ambalangoda" },
    { ID: 1051, Name: "Karandeniya" },
    { ID: 1052, Name: "Elpitiya" },
    { ID: 1053, Name: "Bentota" },
    { ID: 1054, Name: "Balapitiya" },
    { ID: 1055, Name: "Nagoda" },
    { ID: 1056, Name: "Neluwa" },
    { ID: 1057, Name: "Baddegama" },
  ],
  10: [
    { ID: 1058, Name: "Jaffna" },
    { ID: 1059, Name: "Nallur" },
    { ID: 1060, Name: "Kopay" },
    { ID: 1061, Name: "Karaveddy" },
    { ID: 1062, Name: "Chavakachcheri" },
    { ID: 1063, Name: "Point Pedro" },
    { ID: 1064, Name: "Tellippalai" },
    { ID: 1065, Name: "Velanai" },
    { ID: 1066, Name: "Uduvil" },
    { ID: 1067, Name: "Kayts" },
  ],
};

export default DivisionalSecretariats;
