export default {
  items: [
    {
      id: "group-home",
      title: "Home",
      type: "group",
      icon: "feather icon-home",
      DocumentName: "Home",
      children: [
        {
          id: 1,
          title: "Dashboard",
          type: "item",
          icon: "feather icon-home",
          url: "/forms/home/dashboard",
          DocumentName: "Dashboard",
        },
      ],
    },
    {
      id: "group-phi",
      title: "PHI",
      type: "group",
      icon: "icon-navigation",
      DocumentName: "PHI",
      children: [
        {
          id: 1,
          title: "PHI",
          type: "item",
          icon: "feather icon-home",
          url: "/forms/inspection/phi",
          DocumentName: "PHI",
        },
      ],
    },
    {
      id: "group-dgu",
      title: "DGU",
      type: "group",
      icon: "feather icon-home",
      DocumentName: "DGU",
      children: [
        {
          id: 10,
          title: "DGU",
          type: "item",
          icon: "feather icon-copy",
          url: "/forms/dgu/form-list",
          DocumentName: "DGU",
        },
      ],
    },
    // {
    //   id: "group-masters",
    //   title: "Masters",
    //   type: "group",
    //   icon: "icon-navigation",
    //   DocumentName: "Masters",
    //   children: [
    //     {
    //       id: 1000,
    //       title: "Main Masters",
    //       type: "collapse",
    //       icon: "feather icon-grid",
    //       DocumentName: "Main Masters",
    //       children: [
    //         {
    //           id: 1001,
    //           title: "Inventory Master",
    //           type: "item",
    //           url: "/forms/masters/Inventory",
    //           DocumentName: "Inventory",
    //         },
    //         {
    //           id: 1003,
    //           title: "Supplier Master",
    //           type: "item",
    //           url: "/forms/masters/Supplier",
    //           DocumentName: "Supplier Master",
    //         },
    //         {
    //           id: 1005,
    //           title: "Unit Of Measure Master",
    //           type: "item",
    //           url: "/forms/masters/UOM",
    //           DocumentName: "Unit Of Measure Master",
    //         },
    //         {
    //           id: 1006,
    //           title: "Warehouse Master",
    //           type: "item",
    //           url: "/forms/masters/Warehouse",
    //           DocumentName: "Warehouse Master",
    //         },
    //         {
    //           id: 1012,
    //           title: "Inventory Warehouse Master",
    //           type: "item",
    //           url: "/forms/masters/InventoryWarehouseMaster",
    //           DocumentName: "InventoryWarehouseMaster",
    //         },
    //         {
    //           id: 1011,
    //           title: "PR Type",
    //           type: "item",
    //           url: "/forms/masters/PR-Type",
    //           DocumentName: "PR Type",
    //         },
    //         {
    //           id: 1007,
    //           title: "User Branch",
    //           type: "item",
    //           url: "/forms/masters/Create-Branch",
    //           DocumentName: "Create User Branch",
    //         },
    //         {
    //           id: 1008,
    //           title: "User Group",
    //           type: "item",
    //           url: "/forms/masters/Create-Group",
    //           DocumentName: "Create User Group",
    //         },
    //         {
    //           id: 1010,
    //           title: "User Department",
    //           type: "item",
    //           url: "/forms/masters/Department",
    //           DocumentName: "Create User Department",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "group-Masters",
    //   title: "Inquiry",
    //   type: "group",
    //   icon: "feather icon-copy",
    //   DocumentName: "Inquiry",
    //   children: [
    //     {
    //       id: 1100,
    //       title: "Requisition List ",
    //       type: "collapse",
    //       icon: "feather icon-copy",
    //       DocumentName: "Requisition List",
    //       children: [
    //         {
    //           id: 1101,
    //           title: "Requisition List (Summary) ",
    //           type: "item",
    //           url: "/forms/Inquery/Requisition-List",
    //           DocumentName: "Create Requisition List",
    //         },
    //         {
    //           id: 1105,
    //           title: "Requisition List (Item Details) ",
    //           type: "item",
    //           url: "/forms/Inquery/RequisitionDetailList",
    //           DocumentName: "Requisition Detail List",
    //         },
    //         {
    //           id: 1102,
    //           title: "Requisition History Log (Summary) ",
    //           type: "item",
    //           url: "/forms/Inquery/Requisition-History-Log",
    //           DocumentName: "Requisition History Log",
    //         },
    //         {
    //           id: 1104,
    //           title: "Requisition History Log (Details)",
    //           type: "item",
    //           url: "/forms/Inquery/Requisition-History-Log-Details",
    //           DocumentName: "Requisition History Log Details",
    //         },
    //         {
    //           id: 1103,
    //           title: "Pending Documents",
    //           type: "item",
    //           url: "/forms/Inquery/PendingDocuments",
    //           DocumentName: "Pending Documents",
    //         },
    //         {
    //           id: 1107,
    //           title: "KPI",
    //           type: "item",
    //           url: "/forms/Inquery/KPI",
    //           DocumentName: "KPI",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "group-transactions",
    //   title: "Purchase Requisition",
    //   type: "group",
    //   icon: "feather icon-copy",
    //   DocumentName: "Purchase Requisition",
    //   children: [
    //     {
    //       id: 1400,
    //       title: "Purchase Request",
    //       type: "collapse",
    //       icon: "feather icon-copy",
    //       DocumentName: "Purchase-Request",
    //       children: [
    //         {
    //           id: 1401,
    //           title: "Purchase Request",
    //           type: "item",
    //           url: "/forms/Purchase-Request/Purchase-Request",
    //           DocumentName: "Purchase Request",
    //         },
    //       ],
    //     },
    //   ],
    // },
    {
      id: "group-reports",
      title: "Report Details",
      type: "group",
      icon: "feather icon-layout",
      DocumentName: "ReportDetails",
      children: [
        {
          id: 1200,
          title: "Reports",
          type: "collapse",
          icon: "feather icon-layout",
          DocumentName: "Reports",
          children: [
            {
              id: 1201,
              title: "Report",
              type: "item",
              url: "/forms/Reports/Report",
              DocumentName: "Report",
            },
          ],
        },
      ],
    },
    {
      id: "group-admin",
      title: "Administration",
      type: "group",
      icon: "feather icon-settings",
      DocumentName: "Dashboard",
      children: [
        {
          id: 9000,
          title: "Administration",
          type: "collapse",
          icon: "feather icon-settings",
          DocumentName: "Administration",
          children: [
            {
              id: 9001,
              title: "Users",
              type: "item",
              url: "/forms/admin/users",
              DocumentName: "Users",
            },
            // {
            //   id: 9003,
            //   title: "User Permission",
            //   type: "item",
            //   url: "/forms/admin/UserPermission",
            //   DocumentName: "User Permission",
            // },
            // {
            //   id: 9004,
            //   title: "Approval Level",
            //   type: "item",
            //   url: "/forms/admin/approval",
            //   DocumentName: "Approval Level",
            // },
            // {
            //   id: 9005,
            //   title: "Approval Level Mapping",
            //   type: "item",
            //   url: "/forms/admin/Approval-Level-Mapping",
            //   DocumentName: "ApprovalLevelMapping",
            // },
            {
              id: 9006,
              title: "Password Reset",
              type: "item",
              url: "/forms/admin/password-reset",
              DocumentName: "password-reset",
            },
            {
              id: 9007,
              title: "About",
              type: "item",
              url: "/forms/system/about",
              DocumentName: "About",
            },
          ],
        },
      ],
    },
  ],
};
